name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-22.04 ]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Build
        run: ./gradlew build

      - name: capture fabric build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: StackDeobfuscator-Fabric-Artifacts
          path: fabric/build/libs
          if-no-files-found: error

      - name: capture web build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: StackDeobfuscator-Web-Artifacts
          path: web/build/libs
          if-no-files-found: error
